project_id = "rpkawimruhfqhxbpavce"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[functions.category-products]
verify_jwt = false

[functions.analytics-tracker]
verify_jwt = false

[functions.catalog]
verify_jwt = false

[functions.product-detail]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = true

[functions.cancel-redundant-subscriptions]
verify_jwt = true

[functions.cancel-all-subscriptions]
verify_jwt = true

[functions.custom-links]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.get-stripe-prices]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.delete-user-account]
verify_jwt = false

[functions.reset-catalog]
verify_jwt = true

[functions.cleanup-unverified-accounts]
verify_jwt = false

[functions.realtime-visitors]
verify_jwt = false

[functions.admin-metrics]
verify_jwt = false

[functions.admin-stripe-revenue]
verify_jwt = false

[functions.admin-catalog-stats]
verify_jwt = false

[functions.export-users]
verify_jwt = false

[functions.master-login]
verify_jwt = false

[functions.verify-master-token]
verify_jwt = false

[functions.website-tracker]
verify_jwt = false

[functions.admin-website-analytics]
verify_jwt = false

[functions.admin-conversion-funnel]
verify_jwt = false

[functions.capture-lead]
verify_jwt = false

[functions.payment-history]
verify_jwt = true
