project_id = "rpkawimruhfqhxbpavce"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[functions.analytics-tracker]
verify_jwt = false

[functions.catalog]
verify_jwt = false

[functions.product-detail]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = true

[functions.custom-links]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true