
# The local development settings
project_id = "rpkawimruhfqhxbpavce"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[graphql]
enabled = true
port = 54329
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]

[inbound_filters."local_only"]
enabled = true
kind = "local_only"

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[rest]
enabled = true
port = 54323
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]

[realtime]
enabled = true
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[edge_runtime]
enabled = true
port = 54325

[functions.catalog]
verify_jwt = false

[functions.product-detail]
verify_jwt = false
